export const actionTypes = {
  FETCH_RESTAURANTS_START: "FV_FETCH_RESTAURANTS_START",
  FETCH_RESTAURANTS_SUCCESS: "FV_FETCH_RESTAURANTS_SUCCESS",
  LOGIN_START: "FV_LOGIN_START",
  LOGIN_SUCCESS: "FV_LOGIN_SUCCESS",
  SIGNUP_START: "FV_SIGNUP_START",
  SIGNUP_SUCCESS: "FV_SIGNUP_SUCCESS",
  FETCH_RESTAURANT_START: "FV_FETCH_RESTAURANT_START",
  FETCH_RESTAURANT_SUCCESS: "FV_FETCH_RESTAURANT_SUCCESS",
  ADD_ITEM_TO_CART: "FV_ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "FV_REMOVE_ITEM_FROM_CART",
  CREATE_RESTAURANT_START: "FV_CREATE_RESTAURANT_START",
  CREATE_RESTAURANT_SUCCESS: "FV_CREATE_RESTAURANT_SUCCESS",
  UPDATE_RESTAURANT_START: "FV_UPDATE_RESTAURANT_START",
  UPDATE_RESTAURANT_SUCCESS: "FV_UPDATE_RESTAURANT_SUCCESS",
  SET_RESTAURANT_CREATED_TO_FALSE: "FV_SET_RESTAURANT_CREATED_TO_FALSE",
};

export const userTypes = {
  CUSTOMER: "customer",
  RESTAURANT: "restaurant"
};

// to be removed
export const API_ENDPOINT = "http://localhost:4000";