export const actionTypes = {
  FETCH_RESTAURANTS_START: "FV_FETCH_RESTAURANTS_START",
  FETCH_RESTAURANTS_SUCCESS: "FV_FETCH_RESTAURANTS_SUCCESS",
  LOGIN_START: "FV_LOGIN_START",
  LOGIN_SUCCESS: "FV_LOGIN_SUCCESS",
  LOGOUT_START: "FV_LOGOUT_START",
  LOGOUT_SUCCESS: "FV_LOGOUT_SUCCESS",
  SIGNUP_START: "FV_SIGNUP_START",
  SIGNUP_SUCCESS: "FV_SIGNUP_SUCCESS",
  FETCH_RESTAURANT_START: "FV_FETCH_RESTAURANT_START",
  FETCH_RESTAURANT_SUCCESS: "FV_FETCH_RESTAURANT_SUCCESS",
  ADD_ITEM_TO_CART: "FV_ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "FV_REMOVE_ITEM_FROM_CART",
  CREATE_RESTAURANT_START: "FV_CREATE_RESTAURANT_START",
  CREATE_RESTAURANT_SUCCESS: "FV_CREATE_RESTAURANT_SUCCESS",
  UPDATE_RESTAURANT_START: "FV_UPDATE_RESTAURANT_START",
  UPDATE_RESTAURANT_SUCCESS: "FV_UPDATE_RESTAURANT_SUCCESS",
  SET_RESTAURANT_CREATED_TO_FALSE: "FV_SET_RESTAURANT_CREATED_TO_FALSE",
  DELETE_RESTAURANT_START: "FV_DELETE_RESTAURANT_START",
  DELETE_RESTAURANT_SUCCESS: "FV_DELETE_RESTAURANT_SUCCESS",
  ADD_MENU_ITEM_START: "FV_ADD_MENU_ITEM_START",
  ADD_MENU_ITEM_SUCCESS: "FV_ADD_MENU_ITEM_SUCCESS",
  UPDATE_MENU_ITEM_START: "FV_UPDATE_MENU_ITEM_START",
  UPDATE_MENU_ITEM_SUCCESS: "FV_UPDATE_MENU_ITEM_SUCCESS",
  DELETE_MENU_ITEM_START: "FV_DELETE_MENU_ITEM_START",
  DELETE_MENU_ITEM_SUCCESS: "FV_DELETE_MENU_ITEM_SUCCESS",
  PLACE_ORDER_START: "FV_PLACE_ORDER_START",
  PLACE_ORDER_SUCCESS: "FV_PLACE_ORDER_SUCCESS",
  SET_ORDER_PLACED_TO_FALSE: "FV_SET_ORDER_PLACED_TO_FALSE",
  FETCH_ORDER_START: "FV_FETCH_ORDER_START",
  FETCH_ORDER_SUCCESS: "FV_FETCH_ORDER_SUCCESS",
  UPDATE_ORDER_STATUS_START: "FV_UPDATE_ORDER_STATUS_START",
  UPDATE_ORDER_STATUS_SUCCESS: "FV_UPDATE_ORDER_STATUS_SUCCESS",
  SHOW_CLEAR_CART_MODAL: "FV_SHOW_CLEAR_CART_MODAL",
  BLOCK_USER_START: "FV_BLOCK_USER_START",
  BLOCK_USER_SUCCESS: "FV_BLOCK_USER_SUCCESS",
};

export const userTypes = {
  CUSTOMER: "customer",
  RESTAURANT: "restaurant"
};

export const orderStatuses = {
  PLACED: "placed",
  CANCELED: "canceled",
  PROCESSING: "processing",
  IN_ROUTE: "in_route",
  DELIVERED: "delivered",
  RECEIVED: "received"
};

export const orderNextStatusCta = {
  customer: {
    [orderStatuses.PLACED]: "cancel order",
    [orderStatuses.CANCELED]: "",
    [orderStatuses.DELIVERED]: "mark as received",
  },
  restaurant: {
    [orderStatuses.PLACED]: "confirm order",
    [orderStatuses.PROCESSING]: "move to in route",
    [orderStatuses.IN_ROUTE]: "mark as delivered",
  }
};

export const orderNextStaus = {
  customer: {
    [orderStatuses.PLACED]: orderStatuses.CANCELED,
    [orderStatuses.DELIVERED]: orderStatuses.RECEIVED
  },
  restaurant: {
    [orderStatuses.PLACED]: orderStatuses.PROCESSING,
    [orderStatuses.PROCESSING]: orderStatuses.IN_ROUTE,
    [orderStatuses.IN_ROUTE]: orderStatuses.DELIVERED
  }
};

// to be removed
// export const API_ENDPOINT = "http://localhost:4000";
export const API_ENDPOINT = "";